// packages/adapters/vue/src/components/Form.tsx
import { ElForm } from "element-plus";
import { h, defineComponent } from "vue";
import { SectionNode } from "./Section";
import { useFormkl } from "../hooks/useFormkl";

// Equivalent to React.createElement, but for Vue
const createElement = h;

export const FormNode = defineComponent({
  name: "FormNode",
  setup() {
    const { formkl, model } = useFormkl();

    return () => (
      <ElForm ref="elFormRef" model={model.value} labelWidth={130} labelPosition="left">
        {formkl.value.title || formkl.value.description ? (
          <header class="formkl__header">
            {formkl.value.title ? <h2>{formkl.value.title}</h2> : null}
            {formkl.value.description ? <h3>{formkl.value.description}</h3> : null}
          </header>
        ) : null}
        <div class="formkl__body">
          {formkl.value.sections.map((section) => (
            <SectionNode section={section} key={section.key} />
          ))}
        </div>
      </ElForm>
    );
  },
});

// packages/adapters/universal/src/components/Form.tsx
import { Formkl, SchemaBase, SchemaFlat } from "@formkl/shared";
import { SectionNode } from "./Section";

import { FormWrapper } from "./wrappers/FormWrapper";

export const FormNode = (props: {
  formkl: Formkl;
  model: {
    current?: SchemaBase | SchemaFlat;
    value?: SchemaBase | SchemaFlat;
  };
}) => {
  return (
    <FormWrapper>
      {props.formkl.title || props.formkl.description ? (
        <header className="formkl__header">
          {props.formkl.title ? <h2>{props.formkl.title}</h2> : null}
          {props.formkl.description ? <h3>{props.formkl.description}</h3> : null}
        </header>
      ) : null}
      <div className="formkl__body">
        {props.formkl.sections.map((section) => (
          <SectionNode
            section={section}
            key={section.key}
            formkl={props.formkl}
            model={props.model}
          />
        ))}
      </div>
    </FormWrapper>
  );
};
